import { isMac } from '@svgedit/svgcanvas/common/browser';
import * as SvgCanvas from '@svgedit/svgcanvas';
import * as ConfigObj from './ConfigObj.js';
import * as EditorStartup from './EditorStartup.js';
import * as LeftPanel from './panels/LeftPanel.js';
import * as TopPanel from './panels/TopPanel.js';
import * as BottomPanel from './panels/BottomPanel.js';
import * as LayersPanel from './panels/LayersPanel.js';
import * as MainMenu from './MainMenu.js';
import { getParentsUntil } from '@svgedit/svgcanvas/common/util.js';
declare var seConfirm: any;
declare var seAlert: any;
declare class Editor {}
declare const modKey: any;
declare const success: any;
declare const keyHandler: any;
declare const key: any;
declare const elements: any;
declare const parents: any;
declare const o: any;
declare const done: any;
declare const pre: any;
declare const zoom: any;
declare const cnvs: any;
declare const wOrig: any;
declare const hOrig: any;
declare const oldCtr: any;
declare const multi: any;
declare const oldCanY: any;
declare const oldCanX: any;
declare const newCanY: any;
declare const newCanX: any;
declare const offset: any;
declare const ratio: any;
declare const scrollX: any;
declare const scrollY: any;
declare const oldDistX: any;
declare const newX: any;
declare const oldDistY: any;
declare const newY: any;
declare const rule: any;
declare const mode: any;
declare const isNode: any;
declare const mode: any;
declare const elem: any;
declare const ang: any;
declare const mode: any;
declare const isSvgElem: any;
declare const scrbar: any;
declare const zInfo: any;
declare const zoomlevel: any;
declare const bb: any;
declare const parentsUntil: any;
declare const img: any;
declare const icon: any;
declare const runCallback: any;
declare const resolution: any;
declare const zoom: any;
declare const x: any;
declare const y: any;
declare const multi: any;
declare const angle: any;
declare const saveChanges: any;
declare const ok: any;
declare const editingsource: any;
declare const origSource: any;
declare const ok: any;
declare const origSource: any;
declare const oldLayerName: any;
declare const renameLayer: any;
declare const src: any;